# frozen_string_literal: true

require 'rake/testtask'

Rake::TestTask.new(:test) do |t|
  t.libs << 'lib' << 'spec'
  t.pattern = 'spec/**/*_spec.rb'
end

desc 'Run rubocop lint'
task :lint do
  sh 'bundle exec rubocop'
end

task check: %i[lint test]
task default: :check
